ERROR - 2023-08-11 14:45:13 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to tls://mail.persuratan.lldiktiwil16.id:465 (Connection refused) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php:1868
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1868): fsockopen()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1782): CodeIgniter\Email\Email->SMTPConnect()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1667): CodeIgniter\Email\Email->sendWithSmtp()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1565): CodeIgniter\Email\Email->spoolEmail()
#5 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/Activators/EmailActivator.php(32): CodeIgniter\Email\Email->send()
#6 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(185): Myth\Auth\Authentication\Activators\EmailActivator->send()
#7 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
#8 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#10 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}
ERROR - 2023-08-11 14:45:13 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2023-08-11 14:45:13 --> 
ERROR - 2023-08-11 14:50:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'pers_dbsurat'@'localhost' (using password: YES) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(174): mysqli->real_connect()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/appsurat/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#8 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
#7 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
#8 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#13 {main}
CRITICAL - 2023-08-11 14:50:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate()
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt()
 8 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/appsurat/public/index.php')
ERROR - 2023-08-11 14:51:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'pers_dbsurat'@'localhost' (using password: YES) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:174
Stack trace:
#0 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(174): mysqli->real_connect()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/StrictRules/Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique()
#6 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/Validation.php(182): CodeIgniter\Validation\Validation->processRules()
#7 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(154): CodeIgniter\Controller->validate()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#11 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#12 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:218
Stack trace:
#0 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/StrictRules/Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique()
#5 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Validation/Validation.php(182): CodeIgniter\Validation\Validation->processRules()
#6 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(154): CodeIgniter\Controller->validate()
#8 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#13 {main}
CRITICAL - 2023-08-11 14:51:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 427.
 1 SYSTEMPATH/Database/BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Validation/StrictRules/Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/Validation/Validation.php(278): CodeIgniter\Validation\StrictRules\Rules->is_unique()
 5 SYSTEMPATH/Validation/Validation.php(182): CodeIgniter\Validation\Validation->processRules()
 6 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(154): CodeIgniter\Controller->validate()
 8 SYSTEMPATH/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/appsurat/public/index.php')
ERROR - 2023-08-11 15:32:44 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to tls://mail.persuratan.lldiktiwil16.id:465 (Connection timed out) in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php:1868
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1868): fsockopen()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1782): CodeIgniter\Email\Email->SMTPConnect()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1667): CodeIgniter\Email\Email->sendWithSmtp()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1565): CodeIgniter\Email\Email->spoolEmail()
#5 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/Activators/EmailActivator.php(33): CodeIgniter\Email\Email->send()
#6 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(185): Myth\Auth\Authentication\Activators\EmailActivator->send()
#7 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
#8 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#10 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}
ERROR - 2023-08-11 15:32:44 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2023-08-11 15:32:44 --> 
ERROR - 2023-08-11 23:38:28 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for mail.persuratan.lldiktiwil16.id failed: Name or service not known in /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php:1868
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1868): fsockopen()
#2 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1782): CodeIgniter\Email\Email->SMTPConnect()
#3 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1667): CodeIgniter\Email\Email->sendWithSmtp()
#4 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Email/Email.php(1565): CodeIgniter\Email\Email->spoolEmail()
#5 /var/www/html/appsurat/vendor/myth/auth/src/Authentication/Resetters/EmailResetter.php(32): CodeIgniter\Email\Email->send()
#6 /var/www/html/appsurat/vendor/myth/auth/src/Controllers/AuthController.php(249): Myth\Auth\Authentication\Resetters\EmailResetter->send()
#7 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptForgot()
#8 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController()
#9 /var/www/html/appsurat/vendor/codeigniter4/framework/system/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
#10 /var/www/html/appsurat/public/index.php(67): CodeIgniter\CodeIgniter->run()
#11 /var/www/html/appsurat/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}
ERROR - 2023-08-11 23:38:28 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2023-08-11 23:38:28 --> 
CRITICAL - 2023-08-11 23:41:03 --> You do not have sufficient permissions to access that page.
in VENDORPATH/myth/auth/src/Filters/PermissionFilter.php on line 46.
 1 SYSTEMPATH/Filters/Filters.php(173): Myth\Auth\Filters\PermissionFilter->before()
 2 SYSTEMPATH/CodeIgniter.php(471): CodeIgniter\Filters\Filters->run()
 3 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/appsurat/public/index.php')
CRITICAL - 2023-08-11 23:41:22 --> You do not have sufficient permissions to access that page.
in VENDORPATH/myth/auth/src/Filters/PermissionFilter.php on line 46.
 1 SYSTEMPATH/Filters/Filters.php(173): Myth\Auth\Filters\PermissionFilter->before()
 2 SYSTEMPATH/CodeIgniter.php(471): CodeIgniter\Filters\Filters->run()
 3 SYSTEMPATH/CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest()
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/var/www/html/appsurat/public/index.php')
INFO - 2023-08-11 23:52:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-08-11 23:52:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-08-11 23:52:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-08-11 23:52:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-08-11 23:52:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-08-11 23:52:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
